import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/users">
          <h1>Users</h1>
        </Link>
        <Link href="/posts">
          <h1>Posts</h1>
        </Link>
        <Link href="/products">
          <h1>Products</h1>
        </Link>
      </main>
    </>
  );
}
